language: c
os:
  - linux
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install dnsutils
compiler:
  - clang
  - gcc
script:
 - make
 - sudo make install
 - sudo udpxd -l 127.0.0.1:53 -d 8.8.8.8:53
 - sudo udpxd -l [::1]:53 -d [2001:4860:4860::8888]:53
 - dig +nocmd +noall +answer google.de a @127.0.0.1
 - dig +nocmd +noall +answer google.de a @:.1 
 - sudo killall udpxd
