language: c
os:
  - linux
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install dnsutils
compiler:
  - clang
  - gcc
script:
 - make
 - sudo make install
 - sudo udpxd -l 127.0.0.1:53 -d 8.8.8.8:53 &
 - dig +nocmd +noall +answer google.de a @127.0.0.1
 - sudo killall udpxd